### ISSUE TITLE
Replicate database button not supported

### ISSUE THREAD

**Issue by popojargo** [apache/couchdb-fauxton#1007]
## Expected Behavior

1. Log in Fauxton
2. Click on a database ("_global_changes") for example
3. On the top left side bar button, toggle dropdown menu and click on "replicate database".
4. It should open the replication view with the selected database as source?

## Current Behavior

1. Log in Fauxton
2. Click on a database ("_global_changes") for example
3. On the top left side bar button, toggle dropdown menu and click on "replicate database".
4. It will redirect from to http://localhost:8000/#/replication/_global_changes

## Possible Solution

From what I have seen in the code, the following route is supported : `#/replication/_create/:dbname`.
I could simply update the code in order to use the correct link ? 

**Note**: If someone agree with this possible solution, I could easily create a PR to fix this.

## Steps to Reproduce (for bugs)

See current behavior.

## Context

I was just comparing fauxton in chrome vs IE11.

## Your Environment
* Version used:  v. 2.0.0-1111e60
* Browser Name and version: Google chrome (62)
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by popojargo** [comment]
@garrensmith  If you can confirm that the solution I proposed is valid, I will fix this and add tests.

**Comment by garrensmith** [comment]
Hey @popojargo that is correct. If you could fix this, that would be great. Thank you

**Comment by popojargo** [comment]
Fixed with #1014
