### ISSUE TITLE
Update Cluster setup to use Redux

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-fauxton#1016]
The cluster [setup](https://github.com/apache/couchdb-fauxton/tree/master/app/addons/setup) module is a little behind and still uses backbone models and collections. We moving away from that to using a more traditional React/Redux setup. We need to refactor the cluster setup module to use React and Redux. The [Permissions](https://github.com/apache/couchdb-fauxton/tree/master/app/addons/permissions) module is a good example of a Redux setup.

**Comment by garrensmith** [comment]
@popojargo I was wondering if you would be interested in working on this. Its quite a nice challenge to work on. I'm happy to collaborate with you or help you in any way.

**Comment by popojargo** [comment]
@garrensmith  Sure, I'll take a loot at it

**Comment by popojargo** [comment]
Closed with #1045
