### ISSUE TITLE
Package.json missing 'query-string' package

### ISSUE THREAD

**Issue by xft843** [apache/couchdb-fauxton#1033]
During 'Building Fauxton', when **_npm install --production && ./node_modules/grunt-cli/bin/grunt couchdb_** cmds take places, the following errors occur:

ERROR in ./app/addons/documents/index-results/api.js
Module not found: Error: Can't resolve 'query-string' in '/tmp/couchdb/src/fauxton/app/addons/documents/index-results'
 @ ./app/addons/documents/index-results/api.js 24:19-42
 @ ./app/addons/documents/layouts.js
 @ ./app/addons/documents/routes-index-editor.js
 @ ./app/addons/documents/routes.js
 @ ./app/addons/documents/base.js
 @ ./app/load_addons.js
 @ ./app/main.js
 @ multi core-js/fn/array core-js/fn/symbol core-js/fn/promise ./app/main.js

ERROR in ./app/addons/documents/mango/mango.api.js
Module not found: Error: Can't resolve 'query-string' in '/tmp/couchdb/src/fauxton/app/addons/documents/mango'
 @ ./app/addons/documents/mango/mango.api.js 22:19-42
 @ ./app/addons/documents/mangolayout.js
 @ ./app/addons/documents/routes-mango.js
 @ ./app/addons/documents/routes.js
 @ ./app/addons/documents/base.js
 @ ./app/load_addons.js
 @ ./app/main.js
 @ multi core-js/fn/array core-js/fn/symbol core-js/fn/promise ./app/main.js

ERROR in ./app/addons/documents/index-results/containers/ApiBarContainer.js
Module not found: Error: Can't resolve 'query-string' in '/tmp/couchdb/src/fauxton/app/addons/documents/index-results/containers'
 @ ./app/addons/documents/index-results/containers/ApiBarContainer.js 13:19-42
 @ ./app/addons/documents/layouts.js
 @ ./app/addons/documents/routes-index-editor.js
 @ ./app/addons/documents/routes.js
 @ ./app/addons/documents/base.js
 @ ./app/load_addons.js
 @ ./app/main.js
 @ multi core-js/fn/array core-js/fn/symbol core-js/fn/promise ./app/main.js

Problem occurs because 'query-string' package is necessary, but the package.json does not include said package.

**Comment by Antonio-Maranhao** [comment]
Fixed in #1035
