### ISSUE TITLE
[Feature request]Hide non authorized databases from database list

### ISSUE THREAD

**Issue by popojargo** [apache/couchdb-fauxton#1037]
## Expected Behavior

I think we should hide non-authorized databases from the database list instead of showing an error message (Database failed to load...)

## Current Behavior

If  a CouchDB's user doesn't have the permissions to a set of databases, they will be shown and they'll have a message saying that the database failed to load.

So for example, if user X has access to the last database. He has to go through all the databases pages (which can be long if you have multiple databases). I think it would be easier for the user if only the databases that he has access to are shown.

## Possible Solution

a) When we receive a 403 HTTP code  from database requests, we should remove the database entry from the list. 

b) We could maybe have an option to show only the databases that the user has access. Since CouchDB does allow all the users to the see the database list, it's up to the user to decide if they want to see them or not even if they don't have access to it.

# Main problems to deal with

CouchDB can have a lot of databases (with per user pattern, this can be 100). The only way to know if a user has access to it is by querying the database enpoint. So if the 10 databases that you have access are at position 50 000/100 000, that means that we would need to make 50k http queries before we can get the databases that we have access to (which is really not optimal).

What do you think about this proposal?

**Comment by salsa-dev** [comment]
The same is true for GET queries to an API `/_all_dbs`. It should not return the list of all databases on the server. Otherwise it is an information disclosure issue which leads to security problem.

**Comment by Antonio-Maranhao** [comment]
Definitely a nice feature to have but I don't think we can provide a good solution without API support from `/_all_dbs`
@popojargo 
Option A assumes we'd need to cache which DBs are not accessible, which has its own issues: e.g. how long would it be valid (page refresh, session, etc)? how do I refresh since DB is no longer visible?
Option B is essentially option A on auto-mode since the GUI (not the user) would be 'pinging' each DB to find out what's accessible. And unfortunately has the same drawbacks plus not being scalable as you already mentioned.

**Comment by popojargo** [comment]
@Antonio-Maranhao  I discussed with Jan  yesterday and having a new API endpoint would be required for this feature. For example, we could have an index that index databases per user based on their permissions. When we would create/delete databases and update databases permissions, we would need to update this index.

**Comment by Antonio-Maranhao** [comment]
@popojargo that's great you started the conversation already. :) 
If/when there's an issue opened for it, could you link it here?

**Comment by popojargo** [comment]
Closed on behalf of: https://github.com/apache/couchdb/pull/1440

**Comment by PepperTeasdale** [comment]
I'm confused, is this feature really available now? I know I can set the `admin_only_all_dbs` option, but then my user can't see any dbs in the index, even the ones they own. We have a multi-tenant cluster where users have access to fauxton. We would rather they not see the names of other users' dbs, but they still should see their own in the index view.

**Comment by jlami** [comment]
Fauxton also 'hangs' when _all_dbs gets the 401, in a way that even the manual database selection is not working. So there is no way to go to a database you do have access to, without knowing the actual fauxton URL.
