### ISSUE TITLE
faux__jsonlink-link button not working for POST requests

### ISSUE THREAD

**Issue by linquize** [apache/couchdb-fauxton#1088]
faux__jsonlink-link button not working for POST requests

## Expected Behavior

Also works for POST requests.

## Current Behavior

Perform a GET request, which is wrong for `_find` and `_explain`

## Steps to Reproduce (for bugs)

1. Open Fauxton, go to Mango Query
2. Enter a query
3. Click faux__jsonlink-link button
4. Error "Only POST allowed"
5. Click Explain button
6. Click faux__jsonlink-link button
7. Error "Only POST allowed"

## Context

Cannot get the whole raw json for `_find` and `_explain`.

## Your Environment

* Version used: CouchDB 2.1.1 (docker image)
* Browser Name and version: Firefox 60
* Operating System and version (desktop or mobile): Ubuntu 16.04 x64

**Comment by popojargo** [comment]
Interesting catch here. The problems is: we can't post from a browser adress bar. 

Instead, should we:

a) Provide a curl command for non-get API calls?
b) Remove the button (there's no point of having a broken button)

**Comment by garrensmith** [comment]
Thanks for the report @linquize but as @popojargo says we can only go GET's via that link.
