### ISSUE TITLE
Errors not showing on the UI.

### ISSUE THREAD

**Issue by progelio** [apache/couchdb-fauxton#1093]
The UI does not display errors when they are encountered. Example: creating a database with name "Cars" will trigger an error due to upper case but this is not visible to the user. The console says that there is a javascript error:

"Uncaught TypeError: t.save(...).done(...).error is not a function..."

I encountered the error on multiple places.

I'm using the latest version of CouchDB (2.1.1) for Windows 10 and latest version of Chrome.

**Comment by popojargo** [comment]
It fixed on the master. It shows this alert box:
![image](https://user-images.githubusercontent.com/9197078/41602348-9bc7eaa6-73a8-11e8-9686-9119cbefe355.png)
