### ISSUE TITLE
Session changes when using different creds for a new replication

### ISSUE THREAD

**Issue by Antonio-Maranhao** [apache/couchdb-fauxton#1096]
The Create Replication page checks the credentials for local databases using the `/_session` endpoint. When different credentials (than the ones used to login to Fauxton) are used, it has the side-effect of setting a new cookie, which effectively changes the user session in Fauxton. 

## Expected Behavior
When creating a new replication, the current user session should be preserved. 

## Current Behavior
The Create Replication page issues a POST to `/_session` to validate the credentials which changes the user session in the browser. 

## Possible Solution
Check credentials using a GET to `/` endpoint along with the `Authorization: Basic <creds_to_check>` header.  

## Steps to Reproduce (for bugs)
1. Login with a username/password 
1. Go to Replication and click on New Replication
1. Select both local source and target databases
1. Select `Username and password` auth for both
1. Use another username for both auths. Make sure username and password are valid
1. Click `Start Replication`
1. Regardless if you got an error or not, reload the page and check on the navbar that your username has changed. This confirms the user session has changed due to a new cookie being set.

## Your Environment
* Version used: latest on master
* Browser Name and version: Any browser
* Operating System and version (desktop or mobile): any OS

**Comment by popojargo** [comment]
Fixed with #1097
