### ISSUE TITLE
Improve JSON search functionality

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-fauxton#1100]
This came up on the users mailing list recently:

> Search functionality. It looks like the browser’s search doesn’t work, since Ace is probably doing virtual scrolling (i.e. only putting the text in the DOM that’s on the screen at the time. Ace appears to have some search functionality, but it would need some UI around it.

The ACE search functionality [seems to be documented](https://ace.c9.io/#api=search&nav=api) at least in part.

**Comment by Antonio-Maranhao** [comment]
Turned out to be a very simple change to enable the search box - PR submitted.

**Comment by Antonio-Maranhao** [comment]
Delivered in #1102
