### ISSUE TITLE
Please cut new Fauxton release (for CouchDB 2.2.0)

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-fauxton#1104]
Hi there,

CouchDB is ready to release 2.2.0. To complete the release process, we'd like a new Fauxton release to be included in the project. This requires tagging a known-good version of couchdb-fauxton. 

There have been a few nice fixes since the last tag (1.1.15, on 1 May), such as search support in the code editor, support for relative Fauxton URLs, replication setup, redux/react improvements and so on.

Would someone from the Fauxton team kindly assist? Thanks!

-Joan

**Comment by wohali** [comment]
If necessary, feel free to cut a release just prior to that commit if you can't fix the problem rapidly.

**Comment by popojargo** [comment]
If necessary, reverting this PR would be a better idea IMO since it's not an improvement, only a refactor.

**Comment by Antonio-Maranhao** [comment]
@popojargo FYI I've tested everything besides Setup and didn't find any other issues.

**Comment by Antonio-Maranhao** [comment]
@popojargo I spoke too soon - found an issue and here's a PR with the fix: https://github.com/apache/couchdb-fauxton/pull/1106

**Comment by wohali** [comment]
@Antonio-Maranhao @popojargo I encourage you to merge #1108 before closing this (!!!) and any other PRs you have that can be merged safely. Otherwise, please cut a new release ASAP, this is one of 3 issues holding up 2.2.0 now.

**Comment by wohali** [comment]
Thanks for merging #1108! Just need a new tag similar to https://github.com/apache/couchdb-fauxton/commit/0caab2b357c8c6ce6fd13eb1d164534408e820c9 with a matching git tag of `v1.1.16` or `v1.2.0` or whatever you want to call it and we're good! :heart_decoration:

**Comment by popojargo** [comment]
@wohali  Can I have an extra delay of 24 hours to fix an issue that I found with the setup view?

**Comment by popojargo** [comment]
#1109 Should be merged before this

**Comment by Antonio-Maranhao** [comment]
Thanks for the fix @popojargo 

@wohali good to go - tag v1.1.16 created
