### ISSUE TITLE
Can only log on in IE11 when deubgger options is open

### ISSUE THREAD

**Issue by RSchade** [apache/couchdb-fauxton#1117]
Another IE11 specific issue...

On 2.2.0RC3 I can log in fine if I have the debugger console open, but it will just refresh the page and not log me in when the debugger console is closed. Logging out doesn't work regardless. I don't see any errors in the debug console but I'm using Fauxton in production mode.

**Comment by popojargo** [comment]
I'm having the same issue on my side. I tried to debug this lately but didn't the specific source of the problem. I can guarantee that I will have time to fix this in the next days. If anyone else can take this issue it would be appreciated.

**Comment by wohali** [comment]
Closed by #1119 .
