### ISSUE TITLE
Do not depend on Internet resources

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-fauxton#1147]
In fixing packaging, I received warnings from the Debian "lintian" checker that our generated HTML files directly reference 3rd party websites for resources, such as mathjax.

It would be nice if we could completely bundle all of our dependencies so that a CouchDB system firewalled from the internet (such as one in production) could still have a fully functional Fauxton from the console, or from another firewalled administrator/client machine.

Is this possible to fix in the npm build process easily?

**Comment by garrensmith** [comment]
Does it say what we depend on externally? I didnt think we depended on anything.

________________________________

**Comment by wohali** [comment]
Mathjax was one of them, but now I can't reproduce the error. Going to close until I can. Thanks.
