### ISSUE TITLE
npm install fauxton fails directly

### ISSUE THREAD

**Issue by Wildfirefox** [apache/couchdb-fauxton#1149]
Hello everybody,

Expected Behavior:
The command npm install fauxton --save installs the fauxton package into a project.

Current behavior:
The command npm install fauxton --save does not install the package because of a failing install of the dev dependency @webcomponents/url 

Steps to reproduce:
npm init a empty project then run the command: npm install --save fauxton

This is the output of the command line:

C:\Users\w010563\Desktop\test>npm install --save fauxton
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated react-range@0.0.7: This module is now under the @mapbox namespace: install @mapbox/react-range instead

> @webcomponents/url@0.7.1 prepack C:\Users\w010563\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-882bcb4c
> npm run build

> @webcomponents/url@0.7.1 build C:\Users\w010563\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-882bcb4c
> gulp

Der Befehl "gulp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webcomponents/url@0.7.1 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @webcomponents/url@0.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\w010563\AppData\Roaming\npm-cache\_logs\2018-10-29T08_22_31_084Z-debug.log
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: @webcomponents/url@git+https://github.com/webcomponents/URL.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\w010563\AppData\Roaming\npm-cache\_logs\2018-10-29T08_22_31_178Z-debug.log

**Comment by popojargo** [comment]
We change our dependency for webcomponent/uri to use the npm link instead of the git url back in june. @wohali Can I bump Fauxton version so we can update the npm package?

**Comment by wohali** [comment]
@popojargo Bump Fauxton anytime you need to - you just need to issue a PR against apache/couchdb to bump the version tag in [this line](https://github.com/apache/couchdb/blob/master/rebar.config.script#L61-L62)

**Comment by popojargo** [comment]
@wohali Actually, I don't think it's necessary to bump the version. We just need to publish the latest release  to npm. Any idea how to do that?

**Comment by wohali** [comment]
@popojargo I don't have access, but I expect @garrensmith does.

**Comment by wohali** [comment]
Also @michellephung might have access?

**Comment by michellephung** [comment]
@popojargo try this to publish

$ npm version
$ git log
$ git tag
$ git show
$ git push --tags upstream master <—pushes tags to git origin
$ npm publish

**Comment by popojargo** [comment]
@michellephung I don't have the permissions to publish. Do I need to be a contributor?

**Comment by michellephung** [comment]
@popojargo hmm.. i think so. let me try an add you

**Comment by michellephung** [comment]
ok so i don't know how to do that but i did release a new tag with you latest tag

**Comment by popojargo** [comment]
@Wildfirefox  let us know if the updated package works on your side.

**Comment by Wildfirefox** [comment]
@popojargo It seems to work with the updated package. Thx for the fast reply on this issue.
