### ISSUE TITLE
Creating database or documents with Fauxton UI is not reflected in the HTTP interface and vice versa

### ISSUE THREAD

**Issue by jtmorrisbytes** [apache/couchdb-fauxton#1157]
## Expected Behavior

Creating a database and documents with the Fauxton UI Should be reflected when making HTTP api calls
## Current Behavior

When creating databases or documents, the items in question will appear on Fauxton if created on Fauxton, but not when made through HTTP Requests. likewise, items created using HTTP requests would not appear on the Fauxton UI. when said items are created from each end, even documents with the same _id string are allowed to exist, even though their contents are completely different

however, I noticed while opening a document on the fauxton ui, with the path `http://127.0.0.1:5984/_utils/#database/<database_name>/<document_name>` the web console said that
[fauxton refused to create a worker from blob](https://github.com/apache/couchdb-fauxton/files/2568889/fauxton-1541892270119.log).

## Possible Solutions

I Have tried the following:
1. ensuring that I have the latest version of couchdb.
2. restarting the daemon using systemctl.
## Steps to Reproduce (for bugs)

1. follow the normal workflow to create a database or document in Fauxton.
2. make an HTTP api call to the server requesting information on the database
3. no object was found
4. create the a item with the same name/ID but different content and send it over the HTTP API
5. no errors returned, document/database created successfully.
6. check Fauxton for changes, no new or updated documents or databases

## Context

I was attempting to explore the basic Fauxton UI and make get/put requests as an adminisrator. the tests were run using postman and authentication was handled using basic auth. I was using custom _id strings but included no special characters
## Your Environment

* Version used: 2.2.0
* Browser Name and version: chrome 70.0.3538.77 
* Operating System and version (desktop or mobile): ubuntu 18.04
* Link to your project:

**Comment by popojargo** [comment]
@jtmorrisbytes What were your API calls?

**Comment by jtmorrisbytes** [comment]
It’s been a year since I’ve played around with fauxton. I wish I had that information but it’s gone now.
