### ISSUE TITLE
how to configure the pagination to show more than 20 database per page

### ISSUE THREAD

**Issue by veto64** [apache/couchdb-fauxton#1167]
how can i configure the pagination to show more than 20 databases per page?

## Expected Behavior
a database pagination settings

## Current Behavior
cannot find to change it.

## Possible Solution
document it somewhere how to change or add a setting options to the website

## Steps to Reproduce (for bugs)
just have more than 20 databases

## Context
its annoying to click constantly the pagination links

## Your Environment

* Version used: 2.3.0
* Browser Name and version: firefox
* Operating System and version (desktop or mobile): debian9
* i like couchdb very much!

**Comment by Antonio-Maranhao** [comment]
Delivered in #1168
