### ISSUE TITLE
Better Mango Query errors

### ISSUE THREAD

**Issue by rdewolff** [apache/couchdb-fauxton#1173]
## Expected Behavior
When our queries have errors, I would like a *relevant error message* telling me what is causing the error and on what line.

## Current Behavior
Currently, when I write a Mango Query in Fauxton with an error, I don't get any error message. I just see "No document found" and I don't see any "Executed in X ms" message.

## Possible Solution
A better query builder would be nice!

## Context
During dev, we are using the query builder to test some queries quickly. To assist us building new ones or simply play around with the DB to validates our DB state.

## Your Environment

* Version used: 2.2.0 & 2.3.0
* Browser Name and version: Firefox Developer Edition 65.0b12 (64-bit)
* Operating System and version (desktop or mobile): macOS 10.14.2
* Link to your project: internal

**Comment by rdewolff** [comment]
Maybe there are some other tools to help interacting with CouchDB?

**Comment by garrensmith** [comment]
Try running the _explain button. It will give you a bit more information.

**Comment by rdewolff** [comment]
When there is an errror in your querry, this button has no effect...

**Comment by garrensmith** [comment]
Can you provide an example of a query that gives the error.


________________________________

**Comment by rdewolff** [comment]
On the last version available on github, the queries errors are correctly shown. So the problem seems to have been fixed.
Or is there a parameter to enable/disable errors display?

@garrensmith : any wrong query, just add an additional extra `,` somewhere to make your query invalid.

**Comment by garrensmith** [comment]
Great. We have done some fixes around that.


________________________________

**Comment by rdewolff** [comment]
Perfect! Thanks for your fast reactions :)
