### ISSUE TITLE
https

### ISSUE THREAD

**Issue by greg2git** [apache/couchdb-fauxton#1179]
## Expected Behavior
https rather than http only
i don't know how it should be implemented but if it isn't my next choice is to try LevelDB

## Current Behavior
http only when connecting to a remote host

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
start container that has exposed ports
browser different areas of fauxton home page

## Your Environment
standard tcp/ip

**Comment by wohali** [comment]
@greg2git This is provided by CouchDB natively, it just needs configuration.

Documentation is here: https://docs.couchdb.org/en/stable/config/http.html#https-ssl-tls-options

Be sure to firewall off access to port 5984 and only allow port 6984 if you wish to block non-SSL connectivity.
