### ISSUE TITLE
Request for release 2.3.1

### ISSUE THREAD

**Issue by janl** [apache/couchdb-fauxton#1180]
Dear Fauxton team, I’d like to cut a 2.3.1 release, are there any fixes to Fauxton that you’d want to see in there? If yes, could you provide me with a new release tag? Thanks! <3

**Comment by Antonio-Maranhao** [comment]
hi @janl there's a couple of bugs I'd like to fix before cutting a new release. Can you wait until end of tomorrow? 
Otherwise, pls use the current one (1.1.19)

**Comment by janl** [comment]
@Antonio-Maranhao sure, there is no rush :)

**Comment by janl** [comment]
@Antonio-Maranhao one note: this will be a release that does not yet include partitioned dbs.

**Comment by Antonio-Maranhao** [comment]
@janl not to worry. Fauxton checks Couchdb's feature_flags before enabling that functionality in the UI.

**Comment by janl** [comment]
even better :)

**Comment by jaydoane** [comment]
Assuming [this](https://github.com/apache/couchdb/pull/1803) actually fixes [the problem where fauxton setup doesn't result in identical password hashes](https://github.com/apache/couchdb/issues/1781) it might be good to include it as well?

**Comment by Antonio-Maranhao** [comment]
@janl I created a new release: `v1.1.20`

**Comment by janl** [comment]
@Antonio-Maranhao thank you!

**Comment by janl** [comment]
@Antonio-Maranhao ah one more thing, if you’d like to see Fauxton spefcific release notes, can you PR to this PR? 
https://github.com/apache/couchdb-documentation/pull/392 thanks! :)
