### ISSUE TITLE
Google chrome console error, Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by fne** [apache/couchdb-fauxton#1189]
## Expected Behavior

I wanto see the detail of a database with the view pannel.

## Current Behavior

I have a json error and the pannel does not appear

![image](https://user-images.githubusercontent.com/6025622/53225526-9ed14100-3678-11e9-98b6-188e8e14b4d8.png)

## Steps to Reproduce (for bugs)

1.install last image docker of couchdb
2.create a database
3.go to the detail of the database
4.

## Your Environment

* Version used: 2.3.0
* Browser Name and version: Chrome version 72
* Operating System and version (desktop or mobile): windows 7
* Link to your project:

**Comment by Antonio-Maranhao** [comment]
@fne the `unexpected token < in json` means Fauxton got an HTML response instead of a JSON from `https://convertigo-itg.ffr.fr/test`. Assuming that's the url for database `test`, it's likely the request is being served by some other component other than couchdb.

**Comment by Antonio-Maranhao** [comment]
nvm my previous comment... I realized it's related to issue #1188. I submitted a fix in #1191

**Comment by fne** [comment]
Thanks a lot so we're waiting for a new version of couchdb docker image ?

**Comment by Antonio-Maranhao** [comment]
@fne I'm not sure when a new docker mage will be built. If you're pressed on time, you could create your own image using the official one as base.
Essentially 
 - build a new Fauxton release with `grunt release`, which generates the files into `dist/release`
 - build a docker image using something like: 
```
FROM apache/couchdb
# deletes Fauxton files from image
RUN rm -rf /opt/couchdb/share/www
# copies new release from host system into the image
COPY ./dist/release/ /opt/couchdb/share/www/
``` 

Note I haven't tested the code above, you might need to tweak it.

**Comment by wohali** [comment]
New docker image will come with 2.3.1, hopefully this week.

**Comment by fne** [comment]
Thank you

**Comment by jeremysgitty** [comment]
Is anyone still having this issue?

I've just upgraded from 2.1.x to 2.3.1 on Ubuntu using apt-get package install, and I can now successfully run Fauxton when not mounted as '/', though I still seem to having the unexpected token error?

I can view database listing at __all_dbs_, but anything deeper/within a database I get the error.

All seems ok apart from this one, and from looking at this issue I would believe that it would be fixed provided I am running the latest version of couchdb 2.3.1?

![image](https://user-images.githubusercontent.com/40619251/60567389-78e14900-9d9c-11e9-946c-6fd4e6126df7.png)

Do I need to manually update Fauxton in some fashion?  I am not using docker.  Any help would be much appreciated.

Thanks

**Comment by rockeek** [comment]
Hello @jeremysgitty I have the same issue.
But the ticket has been closed. Can we do somthing to avoid this error when browsing database documents when serving couchdb in a directory ? (not directly from /)
Thanks in advance!

**Comment by barbalex** [comment]
I am using couchdb v2.3.1 under ubuntu 18.04. Even after updating this still happens. What can I do?
