### ISSUE TITLE
Cursor in editor is off

### ISSUE THREAD

**Issue by thigg** [apache/couchdb-fauxton#1201]
When editing documents in the editor, the cursor is off.
## Expected Behavior

The cursor should be at the same place where text is inserted.

## Current Behavior

The cursor is to the right of where text is inserted. In this image, I just typed "newText".
![I just typed newText](https://user-images.githubusercontent.com/7593137/60532131-e2aa1600-9cfc-11e9-8588-06567e946625.png)

Maybe this console log is important? `Content Security Policy: The page’s settings blocked the loading of a resource at blob:http://10.0.0.10:5984/b4ac63e0-92f7-40db-b18a-08358b85c2b0 (“script-src”).`

## Steps to Reproduce (for bugs)

1. Browsers: Chromium Version 75.0.3770.100 (Offizieller Build) Arch Linux (64-Bit) and Firefox 67.0.4 (64-bit)
2. Couchdb setup created with vagrant from here: https://github.com/thigg/couchdb-testfield
3. Go to 10.0.0.10:5984 and create a document.

## Context

Trying to edit documents via fauxton

## Your Environment

* Couchdb: `{"couchdb":"Welcome","version":"2.3.1","git_sha":"c298091a4","uuid":"1f7cce9f105b2f55fc025e8e2d949580","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
`
* Browser Name and version: Chromium Version 75.0.3770.100 (Offizieller Build) Arch Linux (64-Bit) and Firefox 67.0.4 (64-bit)
* Operating System and version (desktop or mobile): desktop, arch linux
* Link to your project:

**Comment by popojargo** [comment]
Are you seeing the same behavior when editing through this editor: https://ace.c9.io/ ?

**Comment by thigg** [comment]
Yes, same behavior
![image](https://user-images.githubusercontent.com/7593137/61115707-52559900-a493-11e9-8261-c67e816442b6.png)

System:
```
$ uname -a
Linux` hostname 5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux
$  firefox --version
Mozilla Firefox 68.0
```

And i get the warning in the console on  https://ace.c9.io/: 
`Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (929280 px). Occurrences of will-change over the budget will be ignored.`

**Comment by garrensmith** [comment]
Could you file a ticket with the ace editor then. It’s an upstream issue.


________________________________

**Comment by thigg** [comment]
User Error
