### ISSUE TITLE
Content Security Policy violation errors following local development setup when attempting to start dev

### ISSUE THREAD

**Issue by iamgollum** [apache/couchdb-fauxton#1202]
I have been following the guide(s) - `readme.md` and read the guide on contributing. When I execute `npm run dev` with couchdb up 'n running in docker and the `settings.json` modified accordingly, I get a Content Security violation in `Chrome Version 75.0.3770.100 (Official Build) (64-bit)` on the latest `Mac Book Pro` as of this writing:

```
Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

`default-src 'self'` should work for same-origin when applying host: `"http://localhost:5984"`

I was playing around with https://csp-evaluator.withgoogle.com/ using the `defaultHeaderValue` in `devserver.js` but to no avail. (On an unrelated note, Google is saying you can restrict `object src to 'none'` .. new issue?

This is blocking me from completing local development setup and it would be my pleasure to contribute and fix some UI issues I found.

**Comment by popojargo** [comment]
@iamgollum Have you enable CORS on your local CouchDB?

**Comment by iamgollum** [comment]
@popojargo sounds like ... the Readme needs to be updated... let me check ... would not have thought to enable CORS on the couch side of things...

**Comment by iamgollum** [comment]
@popojargo after grepping and find folder by name and bunch of other attempts to find the CouchDB installation directory on my mac, I ended up doing this and it worked: https://github.com/pouchdb/add-cors-to-couchdb

I think this should be mentioned in the Readme? Should I add this to the readme?

**Comment by popojargo** [comment]
You can probably add a note or a FAQ in the CONTRIBUTING.md file :)

**Comment by iamgollum** [comment]
@Poltergeist the config link was broken for me. Ill submit a PR tomorrow. ill tag it under this issue
