### ISSUE TITLE
Is anybody maintaining this repository anymore. It appears most issues from August 2018 and onward have no comments?

### ISSUE THREAD

**Issue by iamgollum** [apache/couchdb-fauxton#1203]

**Comment by popojargo** [comment]
CouchDB is mostly maintained by volunteers and some Cloudants Folks. So it can happens that there are less contributions to the project, especially to Fauxton.

**Comment by iamgollum** [comment]
@popojargo Thank you for your prompt reply. Looking forward to more prompt responses like these ;) and potentially contributing to the community.

**Comment by popojargo** [comment]
I'll try to take a few minutes tonight to help you with your issues and I'll close this issue (since it's not really an issue).

**Comment by iamgollum** [comment]
@popojargo totally, I usually tag it as a `question` but was not sure who to contact directly.
