### ISSUE TITLE
Saving a document does not work. Neither creating a new database works.

### ISSUE THREAD

**Issue by rols2015** [apache/couchdb-fauxton#1242]
Hi Guys, 
Save document does not work for me.
I am getting timeout.
Could someone advice please?
![image](https://user-images.githubusercontent.com/16349586/68853385-e0db6080-06a7-11ea-9b32-ace59ba6e9f8.png)
![image](https://user-images.githubusercontent.com/16349586/68853514-24ce6580-06a8-11ea-8a21-0b60a6fb28cd.png)

**Comment by rols2015** [comment]
When I tested it with WEB API call I get the following error.
PUT $CLOUDANT_HOST/$CLOUDANT_DB/$DOCUMENT_ID&conflicts=true
```{
    "error": "conflict",
    "reason": "Document update conflict."
}
```
When I remove `&conflicts=true` it works well

**Comment by willholley** [comment]
what is your CouchDB setup and how are you running Fauxton? I doubt this is a problem with Fauxton itself - it looks like a problem with the dev proxy to CouchDB.

**Comment by rols2015** [comment]
@willholley I am running a dev server e.g. `npm run dev`

**Comment by rols2015** [comment]
@willholley any suggestion how I can fix it?

**Comment by rols2015** [comment]
thank you so much @willholley for your help today. Based on our discussion we don't need this change in fauxton anymore.
