### ISSUE TITLE
[Question] Notification system

### ISSUE THREAD

**Issue by popojargo** [apache/couchdb-fauxton#1264]
I'm working on the notification system and I can see that most of the system has been migrated to redux except for the legacy "store.js".

See: https://github.com/apache/couchdb-fauxton/commit/2ee7cf7d9d9a36addde90e48a84a3e349ad5e615

@Antonio-Maranhao or anyone, do you have if that file is still useful?

**Comment by Antonio-Maranhao** [comment]
@popojargo I don't think so. Probably my mistake for not removing it back then.
You can just get rid of it now as part of your changes to #1262
