### ISSUE TITLE
[DISCUSS] Simplify setting up non-partitioned databases

### ISSUE THREAD

**Issue by janl** [apache/couchdb-fauxton#1282]
Hey all,

when creating a database, a user now has to decide between creating a partitioned and non-partitioned database. There is nothing wrong with this in principle, but I’d like to suggest a small change:

Instead of a two radio buttons, use a single checkbox to get a partitioned database.

My reasoning is the following:

1. it is an extra step: when folks create a database, they need to do one more thing, even if they want a non-partitioned database.
2. non-partitioned databases are by far the norm. The use-cases for partitioned re relatively small and well defined, and not useful for most applications.
3. the way the control works now is that:
  - the user _has_ to make a choice. that means even new users need to learn about partitioned databases before they can create their first database, which seems excessive.
  - forcing a choice signals that this is an _important_ choice to make, which is true if you want a partitioned database, but you usually do not.
  - the partitioned case is the _first choice_ and it is the _positively phrased_ option. When presented with making a choice here, most users will create a partitioned db and likely suffer consequences.

If instead creating a database would be the text input for entering the database name, and the create button, with a checkbox to enable partitioning, we’d get a default behaviour that is much more in line with the importance of the feature:

1. no choice required by default
2. new users can learn about partitioning if they want to
3. users that know they want partitioning can’t miss this.

So I suggest we make a change from radio buttons to a checkbox that is off by default.

What do you think?

**Comment by michaelbreslin** [comment]
Jan,

Funny that you suggested this.  The first release of partitioned databases for Cloudant had a checkbox as you suggested, see below:
![image](https://user-images.githubusercontent.com/5444542/83022686-dfe19f00-9ff9-11ea-962d-0063457fd948.png)

We noticed a slow uptake of the feature. So we thought it would be better for adoption for customers to have to make a choice in the UI and understand the consequences at database creation time, in which case we landed with this after working with design:
![image](https://user-images.githubusercontent.com/5444542/83022733-f851b980-9ff9-11ea-9e08-dc752022d6f5.png)

Given that partition queries aren't nearly as useful in upcoming architecture changes, I agree with your sentiment on the change back to original checkbox to remove friction from the create database UX.  

@Antonio-Maranhao do we still have the checkbox code around that we can implement in Fauxton?  I would still want to keep the accordion dropdown that explains what a partitioned database is though.

**Comment by Antonio-Maranhao** [comment]
@michaelbreslin it's easy enough to change it back. I preferred the checkbox approach anyway, so I'm +1

**Comment by janl** [comment]
hah, this is great, thanks for the context! :)

**Comment by janl** [comment]
@dottorblaster super late reply, but go have at it :)
