### ISSUE TITLE
add “What’s New” link in sidebar under version number:

### ISSUE THREAD

**Issue by janl** [apache/couchdb-fauxton#1372]
In an effort to get folks read about what is new in CouchDB, there could be a link here in the sidebar, pointing to https://docs.couchdb.org/en/3.2.2-docs/whatsnew/3.2.html with the matching version.

<img width="65" alt="Screenshot 2022-12-06 at 10 27 40" src="https://user-images.githubusercontent.com/11321/205872675-3a35f6e8-1e69-4f43-a09c-b589ebad4b2d.png">

**Comment by Antonio-Maranhao** [comment]
@janl The docs server doesn't seem to have older versions online - e.g. https://docs.couchdb.org/en/3.1.1-docs/whatsnew/3.1.html doesn't work - so the link will probably have to be `https://docs.couchdb.org/en/latest/whatsnew/<VERSION>.html`. Would that work?

**Comment by janl** [comment]
yeah good call!
