### ISSUE TITLE
Is there a way to create an index using Fauxton?

### ISSUE THREAD

**Issue by YakovL** [apache/couchdb-fauxton#1384]
I'd like to fetch sorted docs and as I've figured, to avoid the `no_usable_index` error, I have to create an index. Is this possible to do this via Fauxton? I've searched a bit, read some docs, but don't see any mention of indices. (I'm not quite sure here is the best place for questions, but I haven't found a better one; also, if creating an index via Fauxton is not yet possible, please consider this as a feature request)

### Environment
* Version used: the version on the bottom left is 3.2.2 (not sure whether this is the version of Fauxton or CouchDB though)
* Browser Name and version: Vivaldi 5.6
* Operating System and version: Windows 10 Pro x64

**Comment by Antonio-Maranhao** [comment]
@YakovL there's a 'manage indexes' link on the right for that exact purpose.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/30349380/218113656-968d4100-ed3f-4606-9289-03f6bc771666.png">

Closing since the functionality is already available.
