### ISSUE TITLE
Next Fauxton Release v1.3.0

### ISSUE THREAD

**Issue by nickva** [apache/couchdb-fauxton#1420]
@Antonio-Maranhao, @mharrigan26, @fryjordan,  we're planning on making new Apache CouchDB release (3.4) and usually we tag Fauxton repo around the same time. Before creating a new tag, wanted to reach out to see if there are any changes or PRs we should wait for perhaps. I created a tentative tag v1.3.0 for now to get an idea what the changes might look like: https://github.com/apache/couchdb-fauxton/releases/tag/v1.3.0

**Comment by mharrigan26** [comment]
Hi @nickva, can you wait on the new Fauxton release until this PR is merged https://github.com/apache/couchdb-fauxton/pull/1415? It accompanies the improvements to the `/_explain` endpoint in https://github.com/apache/couchdb/pull/4662 that I believe are a part of CouchDB 3.4. It should be done this week. Does that work with your timeline?

**Comment by nickva** [comment]
@mharrigan26 definitely, let's wait! That's a neat improvement and would be great to have it in 3.4!

**Comment by nickva** [comment]
I saw PR #1415 merged. Thank you! I'll tag a new Fauxton release. Ping if there any other fixes or patches which should be included to go out with 3.4.

**Comment by nickva** [comment]
Closing the issue for now. The latest Fauxton tag is now v1.3.0.
