### ISSUE TITLE
Connecting to a remote db

### ISSUE THREAD

**Issue by mderazon** [apache/couchdb-fauxton#1423]
Hi, trying to run Fauxton locally to connect it to remote db
I installed it via npm and ran it in the browser, but the app is not responsive (assuming because I don't have local couchdb installed ?)

Is there any way to run it standalone without local instance of couchdb installed ?

**Comment by Antonio-Maranhao** [comment]
@mderazon Yes, the short answer is to run the `/bin/fauxton` script providing where your remote CouchDB instance is.

Not sure on your setup so here are more detailed steps starting from scratch. I used a Cloudant instance but it should work just the same with a CouchDB instance.

```
git clone git@github.com:apache/couchdb-fauxton.git
cd couchdb-fauxton
// Install dependencies
npm ci
// Generate the release (i.e. the HTML, CSS, etc artifacts)
npm run couchdb
// Run the './bin/fauxton' script
cd bin
node fauxton --port 8888 --couchdb https://607ea368-5a7e-45ea-a9b3-6c886a086f47-bluemix.cloudant.com/
```

Then open your browser on `http://localhost:8888`

**Comment by mderazon** [comment]
Thanks you !

**Comment by Antonio-Maranhao** [comment]
I'll close the issue but feel free to reach out again if needed.
