### ISSUE TITLE
Suggested PRs to merge for 1.3.1

### ISSUE THREAD

**Issue by xrobau** [apache/couchdb-fauxton#1434]
Fauxton has had some significant changes since 1.3.0, as well as several security fixes, and main should be tagged 1.3.1 (or 1.4.0?) and pulled into the next release of couch.

However, there are a few outstanding PRs that should be merged before that is done - my uneducated and opinionated selection is below:

* https://github.com/apache/couchdb-fauxton/pull/1432 ✅
* https://github.com/apache/couchdb-fauxton/pull/1429 ✅
* https://github.com/apache/couchdb-fauxton/pull/1396 ✅

There are also PRs going back to 2019, which have stagnated - I don't have the knowledge of the project to know how recoverable they are.

**Comment by big-r81** [comment]
Thx 🙏 for your hints.
