### ISSUE TITLE
Problem scrolling to end of a long line in Ace editor

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-fauxton#870]
There's a bug with the Ace editor configuration (full page + elsewhere) where if you have a single very long line of text - long enough to make the horizontal scrollbar appear, you can't scroll to the very end of the line.
This occurs in all browsers. It looks like the editor is failing to take into account the width of the vertical scrollbar, so the final 1 or 2 characters get hidden.

I spent some time investigating this thinking it was our bug, but it turns out to be a bug with Ace itself. I've opened a ticket here: https://github.com/ajaxorg/ace/issues/2360

Taken from https://issues.apache.org/jira/browse/COUCHDB-2586

**Comment by kanchansrivastava** [comment]
Try  window.dispatchEvent(new Event('resize')); This will fix the problem temporarily.

**Comment by hungdh1405** [comment]
I am new to Ace editor, and I have that problem also.
You can try at https://ace.c9.io/#nav=about, and input long text.
But that problem didn't happen at version 1.2.9..
Now i switch to use old version.

**Comment by popojargo** [comment]
I just tested on the ace.c9.io website and I can't see the problem. Can you share a gif of how to reproduce the issue?

**Comment by cbmgit** [comment]
I am facing the same issue in the latest version. 
![image](https://user-images.githubusercontent.com/40800907/54476141-b5a22800-481f-11e9-9f5c-92023cc35179.png)
When I moved to the older version as suggested by hungdh1405, it's working fine.

**Comment by Antonio-Maranhao** [comment]
No longer an issue in Fauxton.
