### ISSUE TITLE
Invalid map/reduce functions do not show an error to the user

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-fauxton#872]
Click: "Create view"
as the map function put in valid javascript, but without the "function wrapper" from CouchDB:
eg.
if (doc.latin_name)
{ emit(doc.latin_name, doc.latin_name.length); }
Couch returns
{"error":"compilation_error","reason":"Compilation of the map function in the 'latin_name_jssum' view failed: Expression does not eval to a function. (\n if(doc.latin_name)
{\n emit(doc.latin_name, doc.latin_name.length);\n }
\n)"}
but Fauxton does not show an error and the button is not pressable any more

Taken from https://issues.apache.org/jira/browse/COUCHDB-2786

**Comment by Antonio-Maranhao** [comment]
@garrensmith This works now. The UI shows the error notification.

**Comment by popojargo** [comment]
@garrensmith  We should close this one as well
