### ISSUE TITLE
Single Node Setup on Fauxton forces non-127.0.0.1 IP

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-fauxton#874]
Single node setups might just want to bind to 127.0.0.1, this could be fore security on the db server, or on a dev machine.
Currently, the setup wizard for the single-node case forces an ip address other than 127.0.0.1, we should not do that 

Taken from https://issues.apache.org/jira/browse/COUCHDB-3139

**Comment by natevw** [comment]
I could not find an explanation for why this is, the check is in the code without comment: https://github.com/apache/couchdb-fauxton/blob/26adff3b033513177121918a25747699bc694e3c/app/addons/setup/resources.js#L40

I am simply running on my laptop, and have no reason/desire to listen on all interfaces. Seems the workaround is to finish the wizard with `0.0.0.0` and then go into configuration and set it to `127.0.0.1`.

**Comment by janl** [comment]
@natevw it’s a limitation that came out of time pressure to get all this together. We should definitely fix this.
