### ISSUE TITLE
Confirmation modal not closable when deleting a configuration option

### ISSUE THREAD

**Issue by millayr** [apache/couchdb-fauxton#887]
When deleting a configuration setting from the Configuration section of the dashboard, users are unable to dismiss the Confirmation modal to prevent the deletion.  Current workaround is to refresh the page.

![image](https://cloud.githubusercontent.com/assets/6378840/24388236/4c3014c2-1347-11e7-9ebf-4474553bb222.png)

Looks like we're setting state of the modal incorrectly:  https://github.com/apache/couchdb-fauxton/blob/master/app/addons/config/components.js#L253

**Comment by popojargo** [comment]
@garrensmith I am not able to reproduce this bug with the current master. I think it should be closed.
