### ISSUE TITLE
addons or couchapp

### ISSUE THREAD

**Issue by gabrielmancini** [apache/couchdb-fauxton#905]
Hello,

   i want create an admin for my application and i am using couchdb, wondering if its possible create this admin as a addon of fauxton or a couchapp and if make sense create as a addon, or even if is a couchapp a best pratice if i can use some fauxton features in my couchapp.

regards

**Comment by garrensmith** [comment]
@gabrielmancini which version of CouchDB are you using? If you are using CouchDB 2.0 it is possible to create an admin via Fauxton but you need to switch to the *5986 port. I would recommend rather to do this via the command line, or script. You need to do it for each node

**Comment by gabrielmancini** [comment]
@garrensmith  how i do that? do u have an walkthrough or some gotchas?

**Comment by garrensmith** [comment]
Which version of Couchdb are you using?

**Comment by gabrielmancini** [comment]
2.0 and cloudant

**Comment by popojargo** [comment]
@garrensmith  I think this can be closed
