### ISSUE TITLE
Navigating back to Mango query from result document should preserve Mango query

### ISSUE THREAD

**Issue by ronjouch** [apache/couchdb-fauxton#916]
## Reproduction scenario

1. Type a Mango query
1. Run query
1. Click the `Edit` (pencil) icon for a result document
1. Click the browser back button to navigate back to the Mango query editor

## Expected

Mango query from step 1. is preserved.

Actually, what about generalizing this "back navigation"? Could Fauxton *always* store the current query in the app state, so that whatever navigation path ending up back in the Mango editor yields the previously-run query? In this case, a "Default query" button would be neat.

## Actual

Mango query from step 1. is lost, and default query is proposed instead :-/

**Comment by garrensmith** [comment]
We now have a list of previously used mango queries you can choose from. And the going back should preserve the mango query.
