### ISSUE TITLE
"View JSON" / "Copy URL" buttons in development fauxton should use the Couch port, not the app port

### ISSUE THREAD

**Issue by ronjouch** [apache/couchdb-fauxton#917]
When running a development version of Fauxton (using `npm run dev`), the "View JSON" / "Copy URL" features currently use the wrong port: they point to fauxton's port rather than the underlying couchdb port:

![wrong-port](https://cloud.githubusercontent.com/assets/522085/25672967/c684db76-3003-11e7-80c9-4b003100468e.png)

**Comment by garrensmith** [comment]
Fauxton uses `window.location` to determine the url, which is fine since with CouchDB it is served from the same url. The dev server will always be port 8000. I don't really see this as an issue.

**Comment by ronjouch** [comment]
@garrensmith thanks for the fast feedback :) .

> *which is fine since with CouchDB it is served from the same url*

No, my CouchDB running in a docker lives on port 5984. What's especially strange with this behavior is that:
* Fauxton *correctly gets data from Couch* (as you can see from `_all_docs` being listed in the background of the screenshot), so it *clearly does know* my CouchDB runs on 5984, not 8000.
* But *these two specific UI actions* seem to use a different mechanism, causing them to instead use the wrong port.

Looks like a bug to me, no?

**Comment by garrensmith** [comment]
I'm not convinced its a bug, since you are running Fauxton in development mode. But if you would like to fix this, that would be great. I can help you get started if you need.

**Comment by ronjouch** [comment]
@garrensmith what would be the expected development setup? Running a locally-compiled CouchDB? (which then I guess serves on 8000 ?)

Thanks for the offer for help 👍, if I find the time to grab this and need help I'll reach out 😃.
