### ISSUE TITLE
Stale options for views

### ISSUE THREAD

**Issue by assafmo** [apache/couchdb-fauxton#921]
Right now it is really hard to see stale results of a view.  
I need to copy the API string and add `stale=ok` or `stale=update_after`.  
It'll be awesome to have this option again, just like Futon had.  
<img src="http://blogs.justenougharchitecture.com/wp-content/uploads/2011/05/MapReduceFuton.gif">

**Comment by hvt** [comment]
I would totally love to see this query option coming back!

**Comment by hvt** [comment]
Is there anything I could do, to help getting this feature in master?

**Comment by garrensmith** [comment]
You can write the code 👍

All misspelling thanks to my iPhone.
________________________________

**Comment by popojargo** [comment]
@garrensmith  This can be closed
