### ISSUE TITLE
Extension and plugin

### ISSUE THREAD

**Issue by gabrielmancini** [apache/couchdb-fauxton#926]
Hello everyone.
There is some example or tutorial, to create plugins or extensions to a stand alone version?

**Comment by garrensmith** [comment]
@gabrielmancini best to look at any folder [here](https://github.com/apache/couchdb-fauxton/tree/master/app/addons). They are all plugins.

**Comment by gabrielmancini** [comment]
but how i add an addon out of this structure.
i wanna add this new addon just configuring the settings.json and point to other folder, 
i other words, is possible install the global command line fauxton and point my-addon ?

**Comment by garrensmith** [comment]
Unfortunately its not possible to do that. You have to build your plugin with Fauxton.

**Comment by gabrielmancini** [comment]
thanks anyway @garrensmith
