### ISSUE TITLE
db security form does not populate with existing object,

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-fauxton#929]
## Expected Behavior
When browsing to `http://<url>/_utils/#/database/dbname/permissions` , the page should reflect the content of the current database `_security` object. It should then allow incremental editing of the object through adding/deleting admin and member users and roles.

## Current Behaviour
When browsing to `http://<url>/_utils/#/database/dbname/permissions` , the page currently shows no data, as if there was no `_security` object in the database.

## Steps to Reproduce
1. `curl -X PUT http://<url>/dbname`
2. Create a user such as `wohali` in `_users` and make it an admin (e.g. by adding it to `[admins]` in `local.ini`)
3. `curl -X PUT http://wohali:password@<url>/dbname/_security -d '{"admins": {"names": [ "wohali" ], "roles": ["foo", "bar"]}, "members": { "names": ["ralph","frank"], "roles":["developers"]}}'` to create the correct db permissions.
4. `curl -X GET http://wohali:password@<url>/dbname/_security` and validate the output
4. Visit `https://<url>/_utils/#/database/dbname/permissions`. None of the populated data in the `_security` object is shown. 

**Note**: in my browser network console the `GET /_security` on that page returns a 401 error. Inspecting the headers for the request does not show the request being made with the correct security context.

## Your Environment
* Version used: CouchDB, master build
* Browser Name and version: Firefox 53.0.3
* Operating System and version (desktop or mobile): Windows 7 x64, desktop

**Comment by lostnet** [comment]
I hit the same issue in Chrome after upgrading to 2.1.0-27147cd and I think it is a bug in the use of fetch: 

[missing credentials](https://github.com/apache/couchdb-fauxton/blob/14b0901df88a909513d8441fcc499023da3524a8/app/addons/permissions/actions.js?utf8=%E2%9C%93#L31) vs. [included credentials](https://github.com/apache/couchdb-fauxton/blob/14b0901df88a909513d8441fcc499023da3524a8/app/addons/permissions/actions.js?utf8=%E2%9C%93#L88) where the default is to [omit](https://fetch.spec.whatwg.org/#concept-request-credentials-mode).

Strangely, this seems to work in firefox which is probably a bug in the whatwg-fetch pollyfill?

**Comment by gambolputty** [comment]
Seems to be related to [this issue](https://github.com/apache/couchdb/issues/741) over at couchdb.
