### ISSUE TITLE
Fauxton only works went mounted to url "/",.

### ISSUE THREAD

**Issue by KpjComp** [apache/couchdb-fauxton#944]
I'm using Fauxton with Express, and when mounted say at url  "/db"..  everything fails..

## Expected Behavior
When mounted at say '/db',  request should be  '/db/_session',..

## Current Behavior
Instead of say requests like -> '/db/_session',  the console is showing requests like -> '/_session'

## Possible Solution
Make the fauxton route path configurable.  

code like -> 
```
    return window.location.origin + '/' + app.utils.safeURLName(database);
```
This is assuming we have everything running at '/'..

## Steps to Reproduce (for bugs)
Run Fauxton from a route like "/db"

## Context
I'm trying to make an express app, that can host website, and fauxton etc.  Assuming everything is @  "/" is not ideal.  So a request say for session would be  '/db/_session' 

## Your Environment
Node
Windows

**Comment by DQvsRA** [comment]
Any guide how to proper solve this?

**Comment by popojargo** [comment]
I'll look into this this weekend

**Comment by popojargo** [comment]
@garrensmith  or @Antonio-Maranhao, some urls are registered as apiurl and other as server (we call this one to access couch). We use the *apiurl* for the raw json query.

As I am in the process to review the routes, I would like to replace `apiurl` with `server` url. Do you have any objections?

This way, we could simply control the base url in the settings.json 🎉

**Comment by wohali** [comment]
It would be great if Fauxton can determine where it's hosted automatically. Imagine hosting CouchDB behind a reverse proxy that places all URLs under `/db/` or something. You won't be able to edit `settings.json` in this situation as CouchDB might be deployed from packages or in a docker container.

**Comment by popojargo** [comment]
By default, it would use relative path. For example, if you access Fauxton from `/db/_utils`, the resolved host would be `/db`

**Comment by garrensmith** [comment]
Making Fauxton use a relative path would be awesome but don't replace apiurl. The apiurl is used for the little json button on the top right so that a user can see the api endpoint.

**Comment by wohali** [comment]
@garrensmith But does that have to be hard-coded at compile time, or can it be dynamically calculated based on runtime information? If the latter I'm all thumbs up :)

**Comment by garrensmith** [comment]
It can be calculated dynamically. We can just look at window.location for the info

________________________________

**Comment by popojargo** [comment]
Yeah, basically, I calculate the absolute urls with the window.location.href and the relative url. PR should be landing today or tomorrow.

**Comment by DQvsRA** [comment]
Great!
Please post an update once it will be done. 
Will this change be included in a snapshot installed from apt-get?

Thank you!

**Comment by wohali** [comment]
It will be included in the next point release of CouchDB (2.2.0) in the official packages.

**Comment by lichtamberg** [comment]
Is the old Futon GUI still available in CouchDB2 somehow? We can't upgrade due to this bug unfortunately.

**Comment by wohali** [comment]
@lichtamberg No, Futon is no longer supported. Recommend you wait until 2.2.0.

**Comment by lichtamberg** [comment]
Thanks for your feedback, is there an ETA when the 2.2.0 will be finished? There are still some bugs open, so I don't know whow long it will take for it to get released?

**Comment by popojargo** [comment]
Closing this since it has been fixed with #1078.

**Comment by popojargo** [comment]
@lichtamberg @DQvsRA  Any chance you can test the RC for CouchDB 2.2 and see if it works as expected?

**Comment by lichtamberg** [comment]
I would like, but I'm not sure how to install it? I'm just using the normal debian package?

**Comment by ceremcem** [comment]
When will it be available for downloading via package managers?

**Comment by popojargo** [comment]
@ceremcem When CouchDB 2.2.0 RC3 will be accepted. Test of this release candidate would be appreciated !
