### ISSUE TITLE
No list of databases shown in IE 11 

### ISSUE THREAD

**Issue by gdelfino** [apache/couchdb-fauxton#949]
In CouchDB 2.1, when using Internet Explorer 11 (Win7) the included Fauxton does not show the list of databases nor a login screen, so it cannot be used. The only thing shown is the navigation bar on the left.

By having the built-in debugger break on all exceptions, I can see that IE complains about a syntax error on the expression "e.querySelectorAll("*,:x") included in vendor.js

**Comment by wohali** [comment]
@garrensmith I can indeed confirm this is a bug as stated. Not sure how much effort we want to put into fixing it.

**Comment by garrensmith** [comment]
If the error is from vendor.js it means that one of the libraries that we depend on is failing.

**Comment by bagguley** [comment]
@wohali Are you serious? You're not sure how much effort to put into this? CouchDB is now unusable unless you install Firefox because Chrome doesn't even render anything on the page. It's appalling that such simple testing wasn't conducted before release. The exception that @gdelfino referred to is probably a red herring because jQuery (which I presume is where it's occurring) handles these exceptions, they are expected.

Chrome has around 60% of the browser share of desktop browser usage with Firefox bumbling around 6  to 10%. I suggest that this should be top priority.

**Comment by garrensmith** [comment]
Hi @bagguley,

That's a pretty aggressive tone. You are the first person to report it doesn't work on Chrome. Could you provide more details around that. We do a lot of testing to make sure it works on chrome and Firefox. So I am surprised to hear it doesn't work on it.

Cheers
Garren

All misspelling thanks to my iPhone.
________________________________

**Comment by bagguley** [comment]
Hi @garrensmith

It wasn't meant aggressively, but just in a completely shocked tone. It works in Edge and Firefox but not in IE with the Edge renderer. I'll try and dig out more details tomorrow.

Best regards.

**Comment by wohali** [comment]
Can confirm everything is fine in Chrome. We don't do testing on IE so I'm unsurprised it's broken in IE11...as always we're happy to welcome PRs if you can help us get to the bottom of things.

**Comment by gdelfino** [comment]
There are many enterprises still using Win7/IE 11. And installing an alternative browser is specifically forbidden. Fixing this IMHO is important in order to prevent excuses about why we should not be using CouchDB. We will try to look deeper into what is causing the issue.

**Comment by bagguley** [comment]
After some investigation it looks like the issue could be one or more of the following:

**Comment by popojargo** [comment]
@garrensmith  Could I try to fix this issue with [Babel polyfill](https://babeljs.io/docs/usage/polyfill) ?

**Comment by garrensmith** [comment]
That would be great. I don’t have a IE11 on my machine so I’m not sure the exact issue. But some kind of polyfil should do the job

All misspelling thanks to my iPhone.
________________________________

**Comment by popojargo** [comment]
I added the babel polyfill on my fork and it seems to fix most of the issues. There are some styling issues with the Edge engine that I will need to fix. I'll submit a PR next week

**Comment by garrensmith** [comment]
Awesome. Thanks Alexis.

All misspelling thanks to my iPhone.
________________________________

**Comment by popojargo** [comment]
@garrensmith You can close this one

**Comment by garrensmith** [comment]
Closed thanks to @popojargo
