### ISSUE TITLE
Remove React from devDependencies

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-fauxton#969]
Currently we need React as a devDependency to get the unit tests to run. Ideally it would be nice to remove it.

**Comment by wohali** [comment]
Just to be crystal clear, we can't ship with React as a build dependency at all, even if it's just for tests...

**Comment by huang-x-h** [comment]
FB moving to MIT for React 👍  https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
