### ISSUE TITLE
Order changes in replication view, if you click on an action

### ISSUE THREAD

**Issue by rmehner** [apache/couchdb-fauxton#973]
When I go to the Replication Tab I see a list of replications. When I click on a single item action, like delete, it sometimes changes the order in the background (behind the modal), which is confusing, as I wasn't sure for what replication the action would trigger. Maybe this GIF helps, although it's a bit dark because of the modal

![fauxton-order-changes-when-clicking-on-action](https://user-images.githubusercontent.com/82050/29922183-cc798f90-8e54-11e7-8e8a-cb01eedb54bc.gif)

## Expected Behavior

The order should not change, so it's not confusing the users.

## Current Behavior

See GIF.

## Steps to Reproduce (for bugs)

I didn't have the chance to look into the code, but I suspect it has to do with the different state of the one replication above ("Retrying" versus "Completed")

## Your Environment

* Version used: 2.1.0
* Browser Name and version: Desktop Chrome on macOS, Version 60.0.3112.113 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS 10.12.6
* Link to your project: localhost 😆 

It's not a biggie at all, just wanted to report it so someone can look into it if there's time.

Thanks everyone for you work!

**Comment by garrensmith** [comment]
Thanks for report. I think what is happening is its triggering a re-order on the header.

**Comment by popojargo** [comment]
@garrensmith Fixed with #1019

**Comment by rmehner** [comment]
Thank you for your work all around 👍
