### ISSUE TITLE
Browser autocomplete stores db passwords

### ISSUE THREAD

**Issue by alxndrsn** [apache/couchdb-fauxton#976]
If using basic auth, the replication page in Fauxton on couch 2.0 stores database passwords.

Checked on Chrome, Firefox.

## Expected Behavior

Database passwords probably shouldn't be stored in my browser.

### Chrome

<img width="618" alt="screen shot 2017-09-01 at 12 12 15" src="https://user-images.githubusercontent.com/191496/29965733-1b4f2ac0-8f0f-11e7-92fd-e7ae63080f04.png">

### Firefox

<img width="516" alt="screen shot 2017-09-01 at 11 49 27" src="https://user-images.githubusercontent.com/191496/29965738-1fe5321e-8f0f-11e7-9e2d-72c809dcde18.png">

## Possible Solution

Add `autocomplete="off"` attribute to `<input>` elements which are not `type="password"` but may include passwords.

## Steps to Reproduce (for bugs)

1. go to fauxton replication page
2. start a replication to a remote server
3. reload the replication page
4. start typing in the remote server URL box
5. observe old URLs including basic auth credentials

## Your Environment

* Version used:
<img width="209" alt="screen shot 2017-09-01 at 12 16 14" src="https://user-images.githubusercontent.com/191496/29965781-60043f3e-8f0f-11e7-9050-4d54db6003e0.png">

* Browser Name and version:
  - Firefox 55
  - Chrome 60
* Operating System and version (desktop or mobile): OSX

**Comment by garrensmith** [comment]
We have redesigned the replication section for 2.1 Could you upgrade and test that.

**Comment by Antonio-Maranhao** [comment]
After the page redesign passwords are now entered into a proper password field, so this issue is no longer valid.
