### ISSUE TITLE
While viewing a document, changing the url and hitting enter doesn't change the document editor contents

### ISSUE THREAD

**Issue by SCdF** [apache/couchdb-fauxton#977]
Changing the URL of a document does not change to that document on first try, only if you subsequently hit enter (which results in the browser doing a full page refresh).

## Steps to Reproduce
 - Navigate to some document. The URL in your bar will be `http://blah/_utils/#database/db-name/document-name-1`. You can see the JSON of `document-name-1`
 - Change the URL to another document, say, `http://blah/_utils/#database/db-name/document-name-2`. Hit enter.

## Current Behaviour
 - The **title** changes, `database > document-id`
 - The content of the editor does not change, and is still the old doc

## Expected Behaviour 
 - Both the title and the content change.

Interestingly enough, if you give it an incorrect document id it does boot you back to the db screen telling you that it couldn't find the document, so it's definitely looking for it.

## Your Environment
* Version used: Build with CouchDB 2.1
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): MacOS

**Comment by Antonio-Maranhao** [comment]
Fix submitted in PR #987
